allowBuilds:
  better-sqlite3: true
  core-js-pure: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: true
  sharp: true
patchedDependencies:
  '@shadcn/react@0.3.0': patches/@shadcn__react@0.3.0.patch
