export const PIN_WINDOW = 'pin-window'
export const SAVE_CONFIG = 'save-config'
export const GET_CONFIG = 'get-config'
export const GET_WINDOW_SIZE = 'get-window-size'
export const OPEN_EXTERNAL = 'open-external'
