// Four in-memory variants of Tasks with its adjacent Chats region. No real mutations.
const tasks=[['每日 07:30 帕金森老人服药提醒与记录','Daily at 07:30','Tomorrow 07:30','07:30'],['提醒看今日黄金价格','Daily at 11:00','Tomorrow 11:00','11:00'],['提醒看今日黄金价格','Daily at 16:00','Tomorrow 16:00','16:00'],['3分钟后查询今天的金价并汇报','One time','Sep 3 21:44','21:44']];
const chats=[['NewChat','Today 17:34'],['NewChat','Today 17:27'],['NewChat','Today 16:05'],['提醒看今日黄金价格 · 2026-10-01T03:00:00.000Z · attempt 1','Today 11:09'],['提醒看今日黄金价格','Sep 30 17:28'],['提醒看今日黄金价格','Sep 30 12:03'],['提醒看今日黄金价格 · 2026-09-29T08:00:00.000Z · attempt 1','Sep 29 16:09']];
const names={A:'Compact list',B:'Quiet table',C:'Time groups',D:'List + detail'};
let variant=new URLSearchParams(location.search).get('variant')||'A',filter='All',expanded=-1,chosen=0,dark=false;
const page=document.querySelector('#page');
const status=i=>`<span class="status ${i===3?'success':''}">${i===3?'✓ Completed':'Scheduled'}</span>`;
const filters=()=>`<div class="filters">${['All','Active','History'].map(x=>`<button data-filter="${x}" class="${filter===x?'selected':''}">${x} <span class="count">${x==='All'?4:x==='Active'?3:1}</span></button>`).join('')}</div>`;
const heading=()=>`<div class="heading"><strong>Tasks</strong><span class="count">4</span>${filters()}</div>`;
const visible=()=>tasks.map((t,i)=>[t,i]).filter(([,i])=>filter==='All'||(filter==='Active'?i<3:i===3));
const detail=i=>`<div class="inline-detail">Instructions · ${tasks[i][0]}<br>Schedule · ${tasks[i][1]} · Asia/Shanghai<br>Execution chat · <button>Open chat ↗</button><button class="danger" style="float:right">${i===3?'Remove':'Cancel task'}</button></div>`;
const chatsHtml=()=>`<section class="region"><div class="heading"><strong>Chats</strong><span class="count">38</span><button class="search" aria-label="Search chats">⌕</button></div><div class="scroll">${chats.map(([title,time])=>`<div class="row chatrow" tabindex="0" role="button" aria-label="Open chat"><span class="icon"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg></span><span class="text title">${title}</span><time class="time">${time}</time><span class="chevron">›</span></div>`).join('')}</div></section>`;
function compact(){return heading()+`<div class="scroll">${visible().map(([t,i])=>`<div class="row" data-task="${i}"><span class="chevron">${expanded===i?'⌄':'›'}</span><div class="text"><div class="title">${t[0]}</div><div class="meta">${t[1]}</div></div><div class="right">${i===3?status(i):`<time class="time">${t[2]}</time>`}</div><button class="more" data-menu="${i}" aria-label="Task actions">···</button></div>${expanded===i?detail(i):''}`).join('')}</div>`}
function table(){return heading()+`<div class="tablehead cols"><span>Task</span><span>Next run / Last run</span><span>State</span><span></span></div><div class="scroll table">${visible().map(([t,i])=>`<div class="row cols" data-task="${i}"><div class="text"><div class="title">${t[0]}</div><div class="meta">${t[1]}</div></div><time class="time">${t[2]}</time>${status(i)}<button class="more" data-menu="${i}" aria-label="Task actions">···</button></div>${expanded===i?detail(i):''}`).join('')}</div>`}
function agenda(){return heading()+`<div class="scroll agenda">${['Tomorrow','Completed'].map((group,g)=>{const rows=visible().filter(([,i])=>g===0?i<3:i===3);return rows.length?`<div class="group">${group} <span class="count">${rows.length}</span></div>${rows.map(([t,i])=>`<div class="row" data-task="${i}"><time class="clock">${t[3]}</time><div class="text"><div class="title">${t[0]}</div><div class="meta">${t[1]}${i===3?' · Sep 3':''}</div></div><button class="more" data-menu="${i}" aria-label="Task actions">···</button></div>${expanded===i?detail(i):''}`).join('')}`:''}).join('')}</div>`}
function split(){const t=tasks[chosen];return heading()+`<div class="split"><div class="scroll">${visible().map(([t,i])=>`<div class="row ${chosen===i?'chosen':''}" data-task="${i}"><div class="text"><div class="title">${t[0]}</div><div class="meta">${t[1]} · ${t[2]}</div></div><span class="chevron">›</span></div>`).join('')}</div><aside class="detail"><div class="eyebrow">TASK DETAILS</div><h2>${t[0]}</h2><dl><dt>Status</dt><dd>${status(chosen)}</dd><dt>${chosen===3?'Last run':'Next run'}</dt><dd>${t[2]}</dd><dt>Schedule</dt><dd>${t[1]}</dd><dt>Timezone</dt><dd>Asia/Shanghai</dd></dl><div class="actions"><button class="outline">Open chat ↗</button><button class="outline danger">${chosen===3?'Remove':'Cancel task'}</button></div></aside></div>`}
function render(){if(!names[variant])variant='A';page.className=variant==='C'?'agenda-layout':variant==='D'?'split-layout':'';page.innerHTML=`<section class="region">${({A:compact,B:table,C:agenda,D:split})[variant]()}</section>${chatsHtml()}`;document.querySelector('#switcher').innerHTML=`<span class="prototype-note">PROTOTYPE</span><button data-cycle="-1" aria-label="Previous variant">←</button>${Object.entries(names).map(([k,n])=>`<button data-variant="${k}" class="${variant===k?'selected':''}">${k} · ${n}</button>`).join('')}<button data-cycle="1" aria-label="Next variant">→</button><span class="sep"></span><button id="theme">${dark?'Light':'Dark'}</button>`}
function select(v){variant=v;expanded=-1;const url=new URL(location);url.searchParams.set('variant',v);history.replaceState(null,'',url);render()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.dataset.variant)select(b.dataset.variant);else if(b?.dataset.cycle)select(Object.keys(names)[(Object.keys(names).indexOf(variant)+Number(b.dataset.cycle)+4)%4]);else if(b?.dataset.filter){filter=b.dataset.filter;render()}else if(b?.id==='theme'){dark=!dark;document.documentElement.classList.toggle('dark',dark);render()}else if(b?.dataset.menu){const i=Number(b.dataset.menu);expanded=expanded===i?-1:i;render()}else{const row=e.target.closest('[data-task]');if(row){chosen=Number(row.dataset.task);expanded=expanded===chosen?-1:chosen;render()}}});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName)||e.target.isContentEditable)return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();select(Object.keys(names)[(Object.keys(names).indexOf(variant)+(e.key==='ArrowRight'?1:3))%4])}});render();
