name: Build/release @i

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/krypton

      - name: Install-pnpm
        run: npm install -g pnpm

      - name: Install-dependencies
        run: pnpm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: pnpm build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: pnpm build:mac:ci
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: 'false'

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: pnpm build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
